# Generated by Django 5.0 on 2023-12-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=512)),
                ('familiyasi', models.CharField(max_length=512)),
                ('kasbi', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='KeldiKetdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelish_vaqti', models.DateTimeField(blank=True, null=True)),
                ('ketish_vaqti', models.DateTimeField(blank=True, null=True)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuzatish.xodimlar')),
            ],
            options={
                'db_table': 'keldi_ketdi',
            },
        ),
    ]
