# Generated by Django 5.0 on 2023-12-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuzatish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodimlar',
            options={'verbose_name_plural': 'Xodimlars'},
        ),
    ]
