# Generated by Django 5.0 on 2023-12-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuzatish', '0002_alter_xodimlar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodimlar',
            options={'verbose_name': 'Xodimlar', 'verbose_name_plural': 'Xodimlars'},
        ),
    ]
