# Generated by Django 5.0 on 2023-12-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuzatish', '0003_alter_xodimlar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodimlar',
            options={'verbose_name': 'Xodimlar'},
        ),
    ]
