# Generated by Django 5.0 on 2023-12-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuzatish', '0005_alter_xodimlar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keldiketdi',
            options={'verbose_name_plural': 'KeldiKetdi'},
        ),
        migrations.AlterModelTable(
            name='keldiketdi',
            table=None,
        ),
    ]
