# Generated by Django 5.0 on 2023-12-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzatish', '0006_alter_keldiketdi_options_alter_keldiketdi_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='rasmlar/'),
        ),
    ]
