# Generated by Django 4.2.8 on 2023-12-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzatish', '0007_xodimlar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
